name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - zig_target: x86-linux
            archive_name: linux-x86
          - zig_target: x86_64-linux
            archive_name: linux-x86_64
          - zig_target: aarch64-linux
            archive_name: linux-aarch64
          - zig_target: riscv64-linux
            archive_name: linux-riscv64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Build static library
        run: zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.zig_target }}

      - name: Build shared library
        run: zig build -Doptimize=ReleaseFast -Dshared=true -Dtarget=${{ matrix.zig_target }}

      - name: Prepare artifacts
        run: |
          tar czf csvzero-${{ matrix.archive_name }}.tar.gz -C zig-out .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: csvzero-${{ matrix.archive_name }}.tar.gz
          prerelease: ${{ contains(github.ref, '-') }}
          generate_release_notes: true

  build-mac:
    name: Build Mac
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - zig_target: aarch64-macos
            archive_name: macos-aarch64
          - zig_target: x86_64-macos
            archive_name: macos-x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Build static library
        run: zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.zig_target }}

      - name: Build shared library
        run: zig build -Doptimize=ReleaseFast -Dshared=true -Dtarget=${{ matrix.zig_target }}

      - name: Prepare artifacts
        run: |
          tar czf csvzero-${{ matrix.archive_name }}.tar.gz -C zig-out .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: csvzero-${{ matrix.archive_name }}.tar.gz
          prerelease: ${{ contains(github.ref, '-') }}
          generate_release_notes: true
